[tool.poetry]
name = "gamebox"
version = "1.0.0"
description = "gamebox"
authors = ["glory"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
django = "^5.1.3"
channels = "^4.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
