# Generated by Django 5.1.3 on 2024-12-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liargame', '0004_topic_subtopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(max_length=50),
        ),
    ]
